# Generated by Django 5.0.6 on 2024-07-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessanger',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
