# Generated by Django 5.0.6 on 2024-07-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0006_room_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='rooms', to='messangerREST.usermessanger'),
        ),
    ]
