# Generated by Django 5.0.6 on 2024-07-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0007_alter_room_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
