# Generated by Django 5.0.6 on 2024-07-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0009_usermessanger_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessanger',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messangerREST.usermessanger'),
        ),
    ]
