# Generated by Django 5.0.6 on 2024-07-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0010_remove_usermessanger_room_room_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messangerREST.usermessanger'),
        ),
    ]
