# Generated by Django 5.0.6 on 2024-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0011_alter_room_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
        migrations.AddField(
            model_name='room',
            name='admin',
            field=models.ManyToManyField(null=True, to='messangerREST.usermessanger'),
        ),
    ]
