# Generated by Django 5.0.6 on 2024-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0012_remove_room_admin_room_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ManyToManyField(to='messangerREST.usermessanger'),
        ),
    ]
