# Generated by Django 5.0.6 on 2024-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0013_alter_room_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUserMessanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ManyToManyField(to='messangerREST.room')),
                ('usermessanger', models.ManyToManyField(to='messangerREST.usermessanger')),
            ],
        ),
    ]
