# Generated by Django 5.0.6 on 2024-07-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0014_roomusermessanger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomUserMessanger',
        ),
    ]
