# Generated by Django 5.0.6 on 2024-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerREST', '0015_delete_roomusermessanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessanger',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
